apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: createtree
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: createtree
    app.kubernetes.io/part-of: scaffolding
  name: createtreekyzw
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: createtree
    weight: null
status: {}
