apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ctlog-managectroots
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ctlog-managectroots
    app.kubernetes.io/part-of: scaffolding
  name: ctlog-managectrootsrtoj
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ctlog-managectroots
    weight: null
status: {}
